import { Header } from "@/components/Header";
import type { Metadata } from "next";
import { montserrat } from "./fonts/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased bg-gray-50 dark:bg-gray-900  min-h-screen`}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
